### PR TITLE
fix: Refresh client cert when CA rotation

### LINKED ISSUE #932: Refresh proxy certificates if the client certificate becomes invalid
### Bug Description

When the server CA certificates are rotated using the [Rotate CA Certificate](https://cloud.google.com/sql/docs/mysql/manage-ssl-instance#rotate-server-certificate-cas) operation, the proxy should recognize that the server certificates are no longer valid, and do a refresh operation. 

### Example code (or command)

```Go

```

### Stacktrace

```bash

```

### Steps to reproduce?

1. ?
2. ?
3. ?
...

### Environment

1. OS type and version:
2. Go version:
3. Cloud SQL Go Connector version:

### Additional Details

_No response_

### PR DESCRIPTION
**Pull request by hessjcg**
When client CA is rotated, this can cause TLS read errors after the `Dialer.Dial()` has returned. The certificate should be refreshed. 

This adds logic to the dialer to refresh the connection cache if a TLS error occurs after `net.Conn` is returned to the database driver. 

Fixes #932

### CODE REVIEW

File: dialer.go [hunk 1]
```diff
@@ -461,8 +485,11 @@ func (d *Dialer) removeCached(
 	)
 	d.lock.Lock()
 	defer d.lock.Unlock()
-	c.Close()
-	delete(d.cache, createKey(i))
+	key := createKey(i)
+	if cachedC, ok := d.cache[key]; ok && cachedC == c {
+		delete(d.cache, key)
+	}
```
Comment (jackwotherspoon) [inline dialer.go:491]: nit: can we add a comment around this logic?

What case is this for?

File: dialer_test.go [hunk 2]
```diff
@@ -1174,3 +1174,134 @@ func TestDialerChecksSubjectAlternativeNameAndFails(t *testing.T) {
...
+			mock.InstanceGetSuccess(inst, 2),
+			mock.CreateEphemeralSuccess(inst, 2),
+		},
+		dialerOptions: []Option{
+			WithTokenSource(mock.EmptyTokenSource{}),
+			WithDebugLogger(&dialerTestLogger{t: t}),
+			//WithLazyRefresh(),
+			// Note: this succeeds with lazy refresh, but fails with lazy.
+			// because dialer.ForceRefresh does not block connections while the
+			// refresh is in progress.
```
Comment (jackwotherspoon) [inline dialer_test.go:1198]: I think there is a typo in this comment...?

**Review by jackwotherspoon — CHANGES_REQUESTED** [review]

File: dialer.go [hunk 3]
```diff
@@ -435,7 +437,22 @@ func (d *Dialer) Dial(ctx context.Context, icn string, opts ...DialOption) (conn
 	iConn := newInstrumentedConn(tlsConn, func() {
 		n := atomic.AddUint64(c.openConnsCount, ^uint64(0)) // c.openConnsCount = c.openConnsCount - 1
 		trace.RecordOpenConnections(context.Background(), int64(n), d.dialerID, cn.String())
-	}, d.dialerID, cn.String())
+	},
+		func(err error) {
+			// ignore EOF
```
Comment (enocom) [inline dialer.go:442]: Could we expand this comment on why we're ignoring EOF? I think EOFs are the server sending an RST packet, but that's not obvious knowledge for future maintainers.

File: dialer.go [hunk 4]
```diff
@@ -435,7 +437,22 @@ func (d *Dialer) Dial(ctx context.Context, icn string, opts ...DialOption) (conn
 	iConn := newInstrumentedConn(tlsConn, func() {
 		n := atomic.AddUint64(c.openConnsCount, ^uint64(0)) // c.openConnsCount = c.openConnsCount - 1
 		trace.RecordOpenConnections(context.Background(), int64(n), d.dialerID, cn.String())
-	}, d.dialerID, cn.String())
+	},
+		func(err error) {
```
Comment (enocom) [inline dialer.go:441]: whitespace nit: putting this up a line would make it more obvious it's an argument at a glance.

Alternatively, you could pull this anonymous function out into a variable:

``` golang
errFunc := func(err error) {
  // ...
}
iConn := newInstrumentedConn(/*...*/, errFunc)
```

File: dialer.go [hunk 5]
```diff
@@ -446,12 +463,19 @@ func (d *Dialer) Dial(ctx context.Context, icn string, opts ...DialOption) (conn
 	}
 	return iConn, nil
 }
+func (d *Dialer) isTLSError(err error) bool {
+	if nErr, ok := err.(net.Error); ok {
+		return !nErr.Timeout() && // it's a permanent net error
```
Comment (enocom) [inline dialer.go:468]: Have you manually tested this logic as part of doing a cert rotation to confirm it's working as intended?

File: dialer_test.go (hunk 2 above)
Comment (enocom) [reply dialer_test.go:1198]: +1 This looks like a dev-artifact that isn't true anymore?

File: dialer_test.go [hunk 6]
```diff
@@ -1174,3 +1174,134 @@ func TestDialerChecksSubjectAlternativeNameAndFails(t *testing.T) {
...
+	t.Log("Second attempt should fail...")
+	conn, err := d.Dial(context.Background(), "my-project:my-region:my-instance")
+	if err != nil {
+		t.Fatal("Should be no certificate error after, got ", err)
+	}
+
+	// Expect an error on read. This should trigger the dialer to refresh.
+	_, err = io.ReadAll(conn)
+	if err != nil {
+		t.Log("Got error on read as expected.", err)
```
Comment (enocom) [inline dialer_test.go:1228]: t.Logf("Got error on read as expected: %v")

File: dialer_test.go [hunk 7]
```diff
@@ -1174,3 +1174,134 @@ func TestDialerChecksSubjectAlternativeNameAndFails(t *testing.T) {
...
+
+	// Start the server with new certificates
+	cancel2 := mock.StartServerProxy(t, inst)
+	defer cancel2()
+
+	// Dial a second time. We expect no error on dial, but TLS error on read.
+	t.Log("Second attempt should fail...")
+	_, err := d.Dial(context.Background(), "my-project:my-region:my-instance")
+	if err != nil {
+		t.Log("Got error on dial as expected.", err)
```
Comment (enocom) [inline dialer_test.go:1287]: s/Got/got/

File: dialer_test.go [hunk 8]
```diff
@@ -1174,3 +1174,134 @@ func TestDialerChecksSubjectAlternativeNameAndFails(t *testing.T) {
...
+	} else {
+		t.Fatal("Want dial error, got no error")
```
Comment (enocom) [inline dialer_test.go:1289]: s/Want/want/

File: dialer_test.go [hunk 9]
```diff
@@ -1174,3 +1174,134 @@ func TestDialerChecksSubjectAlternativeNameAndFails(t *testing.T) {
...
+	// Dial again. This should complete after the refresh.
+	t.Log("Third attempt...")
+	testSuccessfulDial(
+		context.Background(), t, d,
+		"my-project:my-region:my-instance",
+	)
+	t.Log("Third attempt OK.")
+}
+
+func TestDialerRefreshesAfterRotateServerCA(t *testing.T) {
```
Comment (enocom) [inline dialer_test.go:1243]: Could this test and the one above be combined into a table test by parameterizing the only differences between the two tests?

File: internal/mock/cloudsql.go [hunk 10]
```diff
@@ -75,11 +75,13 @@ func (f FakeCSQLInstance) serverCACert() ([]byte, error) {
 	if f.signer != nil {
 		return f.signer(f.Cert, f.Key)
 	}
+
 	if f.serverCAMode == "" || f.serverCAMode == "GOOGLE_MANAGED_INTERNAL_CA" {
 		// legacy server mode, return only the server cert
 		return toPEMFormat(f.certs.serverCert)
 	}
 	return toPEMFormat(f.certs.casServerCertificate, f.certs.serverIntermediateCaCert, f.certs.serverCaCert)
+
```
Comment (enocom) [inline internal/mock/cloudsql.go:84]: nit: let's omit these changes from the PR since they're unrelated

File: internal/mock/sqladmin.go [hunk 11]
```diff
@@ -102,38 +102,38 @@ func (r *Request) matches(hR *http.Request) bool {
...
-		PscEnabled:      i.pscEnabled,
-		ServerCaMode:    i.serverCAMode,
-	}
-
 	r := &Request{
 		reqMethod: http.MethodGet,
 		reqPath:   fmt.Sprintf("/sql/v1beta4/projects/%s/instances/%s/connectSettings", i.project, i.name),
 		reqCt:     ct,
 		handle: func(resp http.ResponseWriter, _ *http.Request) {
+			var ips []*sqladmin.IpMapping
```
Comment (enocom) [inline internal/mock/sqladmin.go:110]: Is this a necessary change? Looks like formatting to me?

File: dialer_test.go (hunk 6 above)
Comment (hessjcg) [reply dialer_test.go]: Fixed.

File: dialer_test.go (hunk 9 above)
Comment (hessjcg) [reply dialer_test.go]: Test parameterized.

File: dialer_test.go (hunk 7 above)
Comment (hessjcg) [reply dialer_test.go]: Done.

File: dialer_test.go (hunk 8 above)
Comment (hessjcg) [reply dialer_test.go]: Done.

File: internal/mock/cloudsql.go (hunk 10 above)
Comment (hessjcg) [reply internal/mock/cloudsql.go:84]: Fixed.

File: internal/mock/sqladmin.go (hunk 11 above)
Comment (hessjcg) [reply internal/mock/sqladmin.go:110]: Yes, this is necessary. The Server CA changes during the test. The ServerCaCert response field needs to hold the up-to-date value. Thus, this method needs to create the response at the time that the request is made.

File: dialer.go (hunk 5 above)
Comment (enocom) [reply dialer.go:470]: Might be worth adding an e2e test for this, but otherwise this seems fine.

File: dialer.go [hunk 12]
```diff
@@ -447,23 +465,39 @@ func (d *Dialer) Dial(ctx context.Context, icn string, opts ...DialOption) (conn
...
+	i instance.ConnName, c *monitoredCache, err error,
 ) {
 	d.logger.Debugf(
 		ctx,
 		"[%v] Removing connection info from cache: %v",
 		i.String(),
 		err,
 	)
+
+	// If this instance of monitoredCache is still in the cache, remove it.
```
Comment (enocom) [inline dialer.go:489]: Would we just always call delete, regardless of whether the monitoredCache is present or not in cache?

File: dialer_test.go [hunk 13]
```diff
@@ -1174,3 +1174,126 @@ func TestDialerChecksSubjectAlternativeNameAndFails(t *testing.T) {
...
 }
+
+func TestDialerRefreshesAfterRotateCACerts(t *testing.T) {
+	tcs := []struct {
+		desc            string
+		rotateClientCA  bool
+		wantErrorOnDial bool
+		wantErrorOnRead bool
+		useLazyRefresh  bool
+	}{{
```
Comment (enocom) [inline dialer_test.go:1185]: nit: this isn't consistently formatted as below

File: dialer_test.go [hunk 14]
```diff
@@ -1174,3 +1174,126 @@ func TestDialerChecksSubjectAlternativeNameAndFails(t *testing.T) {
...
+		t.Run(tc.desc, func(t *testing.T) {
+			inst := mock.NewFakeCSQLInstanceWithSan(
+				"my-project", "my-region", "my-instance", []string{"db.example.com"},
+				mock.WithDNS("db.example.com"),
+				mock.WithServerCAMode("GOOGLE_MANAGED_CAS_CA"),
+			)
+
+			opts := []Option{
+				WithTokenSource(mock.EmptyTokenSource{}),
+				//WithDebugLogger(&dialerTestLogger{t: t}),
```
Comment (enocom) [inline dialer_test.go:1217]: Can this be deleted?

File: internal/mock/sqladmin.go (hunk 11 above)
Comment (enocom) [reply internal/mock/sqladmin.go:110]: Got it -- a comment to that effect above `i.serverCACert()` would help future maintainers.

File: dialer_test.go (hunk 14 above)
Comment (hessjcg) [reply dialer_test.go]: I uncommented it. It helps to understand the test.

File: dialer.go (hunk 5 above)
Comment (enocom) [reply dialer.go:470]: Ah got it. I missed that detail. I agree then -- no e2e is fine.

File: dialer.go (hunk 12 above)
Comment (enocom) [reply dialer.go:489]: I see. That's probably an edge case, but also worth solving for. Maybe add a note like, "in the case of multiple goroutines creating cache entries, only purge the cache if it's for a known failed attempt and don't overwrite separate goroutine entries." This is a subtle little detail otherwise.

Comment (enocom) [reply dialer.go:489]: Or maybe just:

``` golang
// If this instance was already removed from the cache or *a separate goroutine* replaced it with
// a new instance, do nothing.
```

**Review by enocom — APPROVED** [review]

**Review by jackwotherspoon — APPROVED** [review]
LGTM ✅ 

Thanks for the extra assist here @enocom 👏
