### PR TITLE
fix: memory leak in database/sql integration

### LINKED ISSUE #161: Memory leak in Postgres  database/sql integration
## Bug Description

There is a memory leak in postgres/pgxv4/postgres.go:60 `func (p *pgDriver) Open(name string) (driver.Conn, error)`
This happens because `stdlib.RegisterConnConfig()` on every connection opening returns new dbURI and stores new instance of `pgx.ConnConfig` to map indexed by dbURI

## github.com/jackc/pgx/v4@v4.15.0/stdlib/sql.go
```go
func (d *Driver) registerConnConfig(c *pgx.ConnConfig) string {
	d.configMutex.Lock()
	connStr := fmt.Sprintf("registeredConnConfig%d", d.sequence)
	d.sequence++
	d.configs[connStr] = c
	d.configMutex.Unlock()
	return connStr
}

```
## How to reproduce
1. Code
```go
creds, _ := google.FindDefaultCredentials(ctx, sqladmin.SqlserviceAdminScope)
_, _ = RegisterDriver("cloud-sql", cloudsqlconn.WithIAMAuthN(), cloudsqlconn.WithTokenSource(creds.TokenSource))
pgClient, err := sql.Open("cloud-sql", "host=... user=... dbname=... sslmode=disable")
pgClient, err := sql.Open("cloud-sql", "host=... user=... dbname=... sslmode=disable")
```
2. Check Driver.configs (github.com/jackc/pgx/v4@v4.15.0/stdlib/sql.go:227), there are 2 entries and map is growing on every new connection.

### PR DESCRIPTION
**Pull request by stepan-romankov**
## Change Description

There is a memory leak in postgres/pgxv4/postgres.go:60 `func (p *pgDriver) Open(name string) (driver.Conn, error)`
This happens because `stdlib.RegisterConnConfig()` on every connection opening returns new dbURI and stores new instance of `pgx.ConnConfig` to map indexed by dbURI

## Relevant issues:

- Fixes #161

### CODE REVIEW

**Comment by kurtisvg** [comment]
Hi @stepan-romankov - Thanks for taking the time to open an issue, identify the cause, and suggest a fix. It's greatly appreciated. 

Are you able to sign the CLA? We need to have the CLA signed before we can leave feedback on your PR or accept the change.

File: postgres/pgxv4/postgres.go [hunk 1]
```diff
@@ -54,15 +58,32 @@ type pgDriver struct {
 //
 // "host=my-project:us-central1:my-db-instance user=myuser password=mypass"
 func (p *pgDriver) Open(name string) (driver.Conn, error) {
-	config, err := pgx.ParseConfig(name)
+	dbURI, err := p.getDbURI(name)
```
Comment (enocom) [inline postgres/pgxv4/postgres.go:61]: Let's just inline this function here.

File: postgres/pgxv4/postgres.go [hunk 2]
```diff
@@ -39,13 +40,16 @@ func RegisterDriver(name string, opts ...cloudsqlconn.Option) (func() error, err
...
+		d:      d,
+		dbURIs: make(map[string]string),
 	})
 	return func() error { return d.Close() }, nil
 }
 
 type pgDriver struct {
-	d *cloudsqlconn.Dialer
+	d      *cloudsqlconn.Dialer
+	mu     sync.Mutex
```
Comment (enocom) [inline postgres/pgxv4/postgres.go:51]: This should probably be a read write mutex.

File: postgres/pgxv4/postgres.go [hunk 3]
```diff
@@ -54,15 +58,32 @@ type pgDriver struct {
...
 }
+
+//getDbURI returns and caches database URI for the connection name
+func (p *pgDriver) getDbURI(name string) (string, error) {
+	var dbURI string
+	var ok bool
+	p.mu.Lock()
+	defer p.mu.Unlock()
+
+	if dbURI, ok = p.dbURIs[name]; !ok {
```
Comment (enocom) [inline postgres/pgxv4/postgres.go:75]: Let's invert the use ok here like so:

``` golang
if dbURI, ok = p.dbURIs[name]; ok {
  return stdlib.GetDefaultDriver().Open(dbURI)
}
```

Then the remainder of the method can be about registering a conn config and finally returning a net.Conn.

**Review by enocom — CHANGES_REQUESTED** [review]
Thanks for sending a fix for this!

**Comment by stepan-romankov** [comment]
> Hi @stepan-romankov - Thanks for taking the time to open an issue, identify the cause, and suggest a fix. It's greatly appreciated.
> 
> Are you able to sign the CLA? We need to have the CLA signed before we can leave feedback on your PR or accept the change.

Should already be done...

**Comment by kurtisvg** [comment]
> Should already be done...
 Unfortunately, I just ran the [CLA check ](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/162/checks?check_run_id=5822114620) and it's still showing up missing. You can follow the instructions in that link to check your status.

**Comment by stepan-romankov** [comment]
> 

Looks ok now.

**Comment by stepan-romankov** [comment]
> Thanks for sending a fix for this!

I implemented all the requested changes. Please review.

File: postgres/pgxv4/postgres.go [hunk 4]
```diff
@@ -39,13 +40,16 @@ func RegisterDriver(name string, opts ...cloudsqlconn.Option) (func() error, err
...
+		dbURIs: make(map[string]string),
 	})
 	return func() error { return d.Close() }, nil
 }
 
 type pgDriver struct {
-	d *cloudsqlconn.Dialer
+	d      *cloudsqlconn.Dialer
+	mu     sync.RWMutex
+	dbURIs map[string]string // key is string in a driver-specific format, value is dbURI for registered connection name
```
Comment (enocom) [inline postgres/pgxv4/postgres.go:52]: Let's make this godoc-style:

``` golang
// dbURIs is a map of DSN to DB URI for registered connection names.
dbURIs map[string]string
```

File: postgres/pgxv4/postgres.go [hunk 5]
```diff
@@ -54,6 +58,17 @@ type pgDriver struct {
 //
 // "host=my-project:us-central1:my-db-instance user=myuser password=mypass"
 func (p *pgDriver) Open(name string) (driver.Conn, error) {
+	var dbURI string
```
Comment (enocom) [inline postgres/pgxv4/postgres.go:61]: nit:

``` golang
var (
  dbURI string
  ok bool
)
```

**Review by enocom — CHANGES_REQUESTED** [review]
Two small things. Otherwise LGTM

File: postgres/pgxv4/postgres.go [hunk 6]
```diff
@@ -54,6 +58,17 @@ type pgDriver struct {
...
+	var ok bool
+
+	p.mu.RLock()
+	dbURI, ok = p.dbURIs[name]
```
Comment (enocom) [inline postgres/pgxv4/postgres.go:65]: I worry a bit about using `name` as the key, simply because another caller could very well re-order the parameters and produce a different key. Is there a better key that we could use here?

Comment (stepan-romankov) [reply postgres/pgxv4/postgres.go:65]: I'm pretty sure that connection string stays more or less immutable in most of the cases, and it's more or less driver specific ... I would suggest not change this at least in this MR.

**Comment by stepan-romankov** [comment]
@enocom done.

**Review by enocom — APPROVED** [review]
Thanks!
